export interface HelpArticle {
  id: string;
  title: string;
  category: string;
  summary: string;
  steps: string[];
  keywords: string[];
}

export const helpArticles: HelpArticle[] = [
  { id: "privacy", title: "How local processing works", category: "Basics", summary: "PDFs are read and changed inside this browser; there is no document-upload endpoint.", steps: ["Open a PDF from your device.", "The source and project state are stored in browser-local storage.", "Exports are generated locally and downloaded or saved as another local project.", "Only explicitly installed OCR language packs may use the network."], keywords: ["privacy","upload","local","offline"] },
  { id: "workspace", title: "Navigate a document", category: "Basics", summary: "Every open PDF has four stable destinations: Read, Edit, Pages, and Tools.", steps: ["Use Read for viewing, search, thumbnails, and outlines.", "Use Edit for changing supported content and adding annotations.", "Use Pages for reorder, rotate, duplicate, delete, and extract.", "Use Tools when you want an outcome such as OCR, crop, protect, compress, accessibility, or print preparation.", "Search Tools or press Ctrl/Cmd + K instead of memorizing specialist workspace names."], keywords: ["workspace","navigation","read","edit","pages","tools","tasks"] },
  { id: "find-task", title: "Find a PDF task", category: "Basics", summary: "Tools and Ctrl/Cmd + K search by user intent rather than internal engine names.", steps: ["Open Tools or press Ctrl/Cmd + K.", "Type the action you want, such as crop, remove metadata, sign, split, redact, OCR, compare, or booklet.", "Choose the matching task.", "If no PDF is open, choose a PDF when prompted.", "Inside an open document, Tools keeps everyday actions grouped by Create, Edit, Pages, Protect, Convert, Review, and Automate."], keywords: ["task","search","command palette","crop","metadata","sign","split"] },
  { id: "pwa-offline", title: "Install and prepare for offline use", category: "Offline & PWA", summary: "The installed app can cache its complete runtime. Project retention and OCR language packs are separate choices.", steps: ["Open Settings and review install/offline readiness.", "Install the PWA when your browser offers it.", "Choose Prevent browser cleanup if you want the browser to avoid automatic project eviction.", "Install any OCR language packs you need before going offline.", "Back up important projects as .lpsproject files even when browser cleanup is prevented."], keywords: ["pwa","install","offline","cleanup","persistent storage","ocr"] },
  { id: "pwa-open-share", title: "Open or share PDFs into the installed app", category: "Offline & PWA", summary: "Supporting browsers can pass PDF/project files through Open with or Share without uploading them.", steps: ["Install PDF Studio as a PWA.", "Use Open with or Share when your operating system offers PDF Studio.", "The file is staged locally until the app imports it.", "If your platform does not support this, use Open PDF or Restore project."], keywords: ["share","open with","file handler","share target"] },
  { id: "viewer", title: "Read, search, and download the original PDF", category: "Read", summary: "Read is for viewing and navigation without changing the PDF.", steps: ["Use the page arrows or page field to navigate.", "Open the viewer side panel for thumbnails, outline, search, and document info.", "Choose Single or Continuous view as needed.", "Download original PDF retrieves the unchanged source; Back up project saves the complete PDF Studio project."], keywords: ["viewer","read","search","original","backup"] },
  { id: "edit", title: "Edit a PDF", category: "Edit & annotate", summary: "Edit contains supported existing-content editing plus added text, images, shapes, markup, comments, links, and visual signatures.", steps: ["Choose Edit.", "Pick a grouped tool from the editor rail.", "Select existing supported content or place new content on a page.", "Use Properties for the selected object.", "Use contextual arrange controls when available.", "Download PDF or Save as project when finished."], keywords: ["edit","text","image","shape","highlight","comment"] },
  { id: "visual-signature", title: "Add a visual signature", category: "Edit & annotate", summary: "A visual signature places a signature appearance on the page; it is not certificate-backed digital signing.", steps: ["Open Edit.", "Choose the signature tool.", "Place and size the signature appearance.", "Export the PDF.", "Use an external trusted signing service if you require certificate-backed cryptographic signing."], keywords: ["signature","sign","visual","certificate","digital signing"] },
  { id: "redaction", title: "Remove sensitive content permanently", category: "Protect & sign", summary: "A redaction mark is only a marker until Apply permanent redactions removes the covered content.", steps: ["In Edit, choose Mark redaction and mark every sensitive region.", "The editor keeps a warning that marks are not permanent.", "Open Tools and choose Apply permanent redactions.", "Review the marked regions and run the redaction operation.", "Validate and download or save the derived PDF."], keywords: ["redact","redaction","secret","permanent","security"] },
  { id: "forms", title: "Fill PDF forms", category: "Protect & sign", summary: "The Fill PDF forms task opens supported interactive text fields, checkboxes, radio buttons, and choice fields.", steps: ["Open Tools and choose Fill PDF forms.", "Select a field on the page or in the field list.", "Enter or choose the new value.", "Review the completed form.", "Save a new PDF/project; the source remains unchanged."], keywords: ["forms","fields","checkbox","fill"] },
  { id: "protect", title: "Sanitize or password-protect a PDF", category: "Protect & sign", summary: "Protection tasks can remove risky active content, flatten supported structures, or create a password-protected copy.", steps: ["Open Tools.", "Search for Sanitize PDF, Password-protect PDF, or Flatten supported PDF content.", "Read the warning describing what will be removed or flattened.", "Create the derived output.", "Keep the original when interactive structures or signatures matter."], keywords: ["protect","password","encrypt","sanitize","flatten"] },
  { id: "organize", title: "Reorder, remove, rotate, or extract pages", category: "Pages", summary: "Pages contains the primary page-organization workflow.", steps: ["Open Pages.", "Click thumbnails or enter a page range.", "Use the built-in examples for odd, even, or exclusions.", "Reorder, rotate, duplicate, delete, reverse, or extract.", "Download or save the validated derived copy."], keywords: ["pages","organize","extract","rotate","range"] },
  { id: "page-tools", title: "Crop, split, or add blank pages", category: "Pages", summary: "Less-frequent page tasks are found through Tools instead of separate workspace modes.", steps: ["Open Tools inside the current PDF.", "Search Crop pages, Split PDF, or Insert blank pages.", "For crop, remember that changing the CropBox hides content but does not securely erase it.", "Create or download the derived result."], keywords: ["crop","split","blank pages","insert","cropbox"] },
  { id: "ocr", title: "Make a scanned PDF searchable", category: "Convert & optimize", summary: "OCR recognizes printed text locally and creates searchable raster PDF output.", steps: ["Open Tools and choose OCR PDF.", "Install the required language pack.", "Choose pages and use Balanced recognition unless you need another quality level.", "Open Advanced image cleanup only for difficult scans.", "Run OCR and create the searchable PDF."], keywords: ["ocr","scan","searchable","language","recognition"] },
  { id: "optimize", title: "Reduce PDF file size", category: "Convert & optimize", summary: "Compress PDF offers lossless cleanup first and stronger image-based compression when a smaller file matters more than preserving every PDF structure.", steps: ["Open Tools and choose Compress PDF.", "Start with lossless optimization when possible.", "Use stronger raster compression only if needed.", "Read What changes? before image-based compression when preservation matters.", "Compare output size and quality before saving."], keywords: ["compress","optimize","file size","lossless"] },
  { id: "toolbox", title: "Watermark, number pages, edit metadata, or export content", category: "Document utilities", summary: "Related utility actions are grouped under Document utilities instead of presented as a separate product subsystem.", steps: ["Open Tools inside the PDF.", "Choose Watermark & page numbers, Edit or remove metadata, Export PDF content, Crop pages, or another utility task.", "The Document utilities disclosure opens the underlying controls when needed.", "Create a derived project for PDF-changing actions or download non-mutating exports."], keywords: ["watermark","page numbers","metadata","grayscale","convert","export"] },
  { id: "merge", title: "Merge PDFs", category: "Create & combine", summary: "Merge combines complete local PDFs in the order you choose.", steps: ["Open Tools and choose Merge PDFs.", "Add PDF files.", "Drag them into the correct order.", "Create the merged PDF.", "Open or download the validated result."], keywords: ["merge","combine"] },
  { id: "scan", title: "Create a PDF from images", category: "Create & combine", summary: "Scan to PDF combines images or camera captures into a new PDF, with optional OCR.", steps: ["Open Tools and choose Scan to PDF.", "Add images or capture pages where your browser supports the camera.", "Reorder and rotate pages.", "Enable OCR only if searchable text is needed.", "Create the PDF."], keywords: ["scan","camera","images","photo"] },
  { id: "compare", title: "Compare two PDFs", category: "Review & accessibility", summary: "Compare automatically aligns matching pages, including scanned pages, before showing text or visual differences.", steps: ["Open Tools and choose Compare PDFs.", "Choose the original and revised PDFs.", "Review the alignment list: same, changed, inserted, or deleted.", "Select a row to compare the matched pages.", "Use text comparison for text-heavy PDFs and visual comparison for appearance changes."], keywords: ["compare","diff","changed","scanned","alignment"] },
  { id: "create", title: "Create a PDF from text, Markdown, or simple HTML", category: "Create & combine", summary: "Create PDF paginates your content locally with metric page controls and reusable style presets.", steps: ["Open Tools and choose Create PDF.", "Choose Markdown, plain text, or simple HTML.", "Set page size, margins, typography, header/footer, and page numbers.", "Use searchable output for normal supported scripts; use visual compatibility when browser shaping is required.", "Preview, then download or save as a project."], keywords: ["create","markdown","html","text","pdf"] },
  { id: "batch", title: "Run the same actions on multiple PDFs", category: "Automate", summary: "Batch automation applies a reusable ordered recipe to several local PDFs.", steps: ["Open Tools and choose Batch automation.", "Add input PDFs.", "Add actions in the order they should run.", "Multi-output actions such as Split or Page images must remain last.", "Save or export the recipe if you want to reuse it.", "Run the queue and download individual outputs or one ZIP."], keywords: ["batch","automation","recipe","multiple"] },
  { id: "accessibility", title: "Check accessibility", category: "Review & accessibility", summary: "Accessibility is an advanced task for document structure, reading order, image descriptions, form descriptions, and related findings.", steps: ["Open Tools and choose Check accessibility.", "Review plain-language findings first.", "Repair supported language, title, form-description, and structure issues where available.", "Use technical details only when a standard or external validator requires them.", "Treat standards-oriented output as a candidate until independently validated where formal certification is required."], keywords: ["accessibility","pdf/a","standards","tags","reading order","alt text"] },
  { id: "print-advanced", title: "Prepare print layout, Bates numbering, or archive readiness", category: "Review & accessibility", summary: "Specialist document tasks remain available without becoming primary workspace tabs.", steps: ["Open Tools.", "Choose Prepare print layout for booklet or imposition work.", "Choose Add Bates numbering for sequential document labels.", "Choose Check archive readiness for PDF/A-oriented findings.", "Use specialist layers or other production controls only when the workflow requires them."], keywords: ["bates","numbering","imposition","booklet","layers","archive"] },
  { id: "inspect-repair", title: "Inspect or repair a problematic PDF", category: "Troubleshooting", summary: "Repair and Document technical details are recovery tasks, not normal editing destinations.", steps: ["Search Tools for Repair PDF when a file is damaged or behaves unexpectedly.", "Search for Document technical details only when you need fonts, forms, actions, signatures, revisions, or resource information.", "Neither task overwrites the source project."], keywords: ["inspect","repair","broken","diagnostics","document details"] },
  { id: "what-changes", title: "Understand the What changes? panel", category: "Document safety", summary: "The optional What changes? panel explains which PDF structures an operation keeps, rebuilds, or may remove.", steps: ["Choose What changes? in the document header when the setting is enabled.", "Read Preserved, Changes, and Possible losses.", "Use it especially before rasterization, redaction, flattening, or other structure-changing operations.", "Close the panel when you no longer need the details."], keywords: ["preservation","what changes","structure","loss"] },
  { id: "history", title: "Use history and checkpoints", category: "Recovery", summary: "History keeps restorable checkpoints prominent while lower-level revision and transaction records stay under Technical history.", steps: ["Open History from the document header.", "Create a named checkpoint before a risky workflow when useful.", "Restore a checkpoint as a separate project if needed.", "Open Technical history only when troubleshooting revision or transaction details."], keywords: ["history","checkpoint","revision","transaction","restore"] },
  { id: "backup", title: "Back up and restore a project", category: "Recovery", summary: "A .lpsproject file contains the source PDF and supported local project state with integrity checks.", steps: ["Choose Back up project from Read or Documents.", "Store the .lpsproject file outside browser storage.", "Use Restore project when needed.", "A checksum or package-consistency failure blocks restoration instead of silently trusting damaged data."], keywords: ["backup","restore","lpsproject","recovery"] },
  { id: "safe-mode", title: "Recover from repeated startup problems", category: "Troubleshooting", summary: "Safe Mode suppresses automatic project reopening and service-worker participation for the current tab.", steps: ["Open Support → Troubleshooting & recovery.", "Enter Safe Mode and reload.", "Run project health or repair the offline cache if needed.", "Export a privacy-safe support bundle only when troubleshooting.", "Exit Safe Mode after the issue is resolved."], keywords: ["safe mode","crash","cache","maintenance"] }
];

export const keyboardShortcuts = [
  ["Ctrl/Cmd + K", "Find a PDF task"],
  ["Ctrl/Cmd + O", "Open a PDF where supported by the active workflow"],
  ["Ctrl/Cmd + S", "Save or export in supported workspaces"],
  ["Ctrl/Cmd + Z", "Undo"],
  ["Ctrl/Cmd + Shift + Z", "Redo"],
  ["Ctrl/Cmd + F", "Search the current PDF"],
  ["Delete", "Delete selected editor objects or organizer pages"],
  ["Arrow keys", "Nudge selected editor objects"],
  ["Escape", "Close dialogs, menus, or the current transient action"]
] as const;
