export interface HelpArticle {
  id: string;
  title: string;
  category: string;
  summary: string;
  steps: string[];
  keywords: string[];
}

export const helpArticles: HelpArticle[] = [
  { id: "privacy", title: "How local processing works", category: "Basics", summary: "PDFs are read and changed inside this browser; there is no document-upload endpoint.", steps: ["Open a PDF from your device.", "The source and project state are stored in browser-local storage.", "Exports are generated locally and downloaded or saved as another local project.", "Only explicitly installed OCR language packs may use the network."], keywords: ["privacy","upload","local","offline"] },
  { id: "workspace", title: "Choose the right workspace", category: "Basics", summary: "Simple mode shows everyday tools. Advanced mode adds specialist inspection, repair, print, accessibility, and structure tools.", steps: ["Use Read for viewing and search.", "Use Edit for visible content and annotations.", "Use Pages for reorder/rotate/extract.", "Use Tools for crop, page numbers, metadata, and conversions.", "Use Forms & Protect for forms, permanent redaction, cleanup, and passwords.", "Switch to Advanced only when you need specialist tools."], keywords: ["simple","advanced","workspace","navigation","tools"] },
  { id: "pwa-offline", title: "Install and prepare for offline use", category: "Offline & PWA", summary: "The installed app can cache its complete runtime. Project retention and OCR language packs are separate choices.", steps: ["Open Install & offline on Home or Settings.", "Install the PWA when your browser offers it.", "Choose Prevent browser cleanup if you want the browser to avoid automatic project eviction.", "Install any OCR language packs you need before going offline.", "Back up important projects as .lpsproject files even when browser cleanup is prevented."], keywords: ["pwa","install","offline","cleanup","persistent storage","ocr"] },
  { id: "pwa-open-share", title: "Open or share PDFs into the installed app", category: "Offline & PWA", summary: "Supporting browsers can pass PDF/project files through Open with or Share without uploading them.", steps: ["Install PDF Studio as a PWA.", "Use Open with or Share when your operating system offers PDF Studio.", "The file is staged locally until the app imports it.", "If your platform does not support this, use Open PDF or Restore project."], keywords: ["share","open with","file handler","share target"] },
  { id: "viewer", title: "Read, search, and download the original PDF", category: "Read", summary: "Read is for viewing only. Use the workspace bar to switch to editing or other document tools.", steps: ["Use the page arrows or page field to navigate.", "Open Pages / search for thumbnails, outline, search, and document info.", "Choose Single or Continuous view as needed.", "Download original PDF retrieves the unchanged source; Back up project saves the complete PDF Studio project."], keywords: ["viewer","read","search","original","backup"] },
  { id: "edit", title: "Edit a PDF", category: "Edit", summary: "Editor tools are grouped by purpose: Navigate, Insert, Shapes, Markup, Review, and Redaction.", steps: ["Choose Edit.", "Pick a grouped tool from the left rail.", "Click or drag on the page to place content.", "Use Properties for the selected object.", "Existing PDF content shows an editing-support label; technical confidence details are optional.", "Download PDF or Save as project when finished."], keywords: ["edit","text","image","shape","highlight","comment"] },
  { id: "redaction", title: "Remove sensitive content permanently", category: "Forms & Protect", summary: "A redaction mark is only a marker until Apply redactions permanently removes the covered content.", steps: ["In Edit, choose Mark redaction and mark every sensitive region.", "The editor keeps a visible warning that marks are not permanent.", "Open Forms & Protect.", "Review the marked regions and choose Apply redactions.", "Validate and download/save the derived PDF."], keywords: ["redact","redaction","secret","permanent","security"] },
  { id: "forms", title: "Fill PDF forms", category: "Forms & Protect", summary: "Use Forms & Protect for interactive text fields, checkboxes, radio buttons, and supported choice fields.", steps: ["Open Forms & Protect.", "Choose the Forms section.", "Select a field on the page or in the field list.", "Enter the new value.", "Save a new PDF/project; the source remains unchanged."], keywords: ["forms","fields","checkbox","fill"] },
  { id: "protect", title: "Password-protect or clean a PDF", category: "Forms & Protect", summary: "Protection tools can remove risky active content, flatten supported structures, or create a password-protected derived copy.", steps: ["Open Forms & Protect.", "Choose the security action you actually need.", "Read the warning describing what will be removed or flattened.", "Create the derived output.", "Keep the original when interactive structures or signatures matter."], keywords: ["protect","password","encrypt","sanitize","flatten"] },
  { id: "organize", title: "Reorder, remove, rotate, or extract pages", category: "Pages", summary: "Use Pages for page-level changes without entering the visual editor.", steps: ["Open Pages.", "Click thumbnails, or type a range such as 1-5.", "Use the built-in examples for odd, even, or exclusions.", "Reorder, rotate, duplicate, delete, reverse, or extract.", "Download or save the validated derived copy."], keywords: ["pages","organize","split","extract","rotate","range"] },
  { id: "ocr", title: "Make a scanned PDF searchable", category: "OCR", summary: "OCR recognizes page images locally. Everyday quality choices are Fast, Balanced, and Best recognition.", steps: ["Install the required language pack.", "Choose pages.", "Choose Balanced unless speed or very small text requires another quality.", "Open Advanced image cleanup only for difficult scans.", "Run OCR and review results.", "Create the searchable PDF."], keywords: ["ocr","scan","searchable","language","recognition"] },
  { id: "optimize", title: "Reduce PDF file size", category: "Optimize", summary: "Optimize offers lossless cleanup first and stronger image-based compression when smaller size matters more than preserving every structure.", steps: ["Open Optimize.", "Start with lossless optimization when possible.", "Use stronger raster compression only if needed.", "Read the preservation warning before image-based compression.", "Compare output size and quality before saving."], keywords: ["compress","optimize","file size","lossless"] },
  { id: "toolbox", title: "Crop, number pages, watermark, or edit metadata", category: "Tools", summary: "PDF Tools collects everyday document utilities and local conversions.", steps: ["Open Tools inside the document workspace.", "Choose the needed utility: crop, decoration, metadata, blank pages, conversion, split, or grayscale.", "Enter measurements in millimetres where applicable.", "Create a derived project for PDF-changing actions, or download non-mutating exports."], keywords: ["crop","watermark","page numbers","metadata","grayscale","convert"] },
  { id: "merge", title: "Merge PDFs", category: "Quick tools", summary: "Merge combines complete local PDFs in the order you choose.", steps: ["Open Tools → Merge PDFs.", "Add PDF files.", "Drag them into the correct order.", "Create the merged PDF.", "Open or download the validated result."], keywords: ["merge","combine"] },
  { id: "scan", title: "Create a PDF from images", category: "Quick tools", summary: "Scan to PDF combines images or camera captures into a new PDF, with optional OCR.", steps: ["Open Tools → Scan to PDF.", "Add images or capture pages where your browser supports the camera.", "Reorder and rotate pages.", "Enable OCR only if searchable text is needed.", "Create the PDF."], keywords: ["scan","camera","images","photo"] },
  { id: "compare", title: "Compare two PDFs", category: "Quick tools", summary: "Compare automatically aligns matching pages, including scanned pages, before showing text or visual differences.", steps: ["Open Tools → Compare PDFs.", "Choose the original and revised PDFs.", "Review the alignment list: same, changed, inserted, or deleted.", "Select a row to compare the matched pages.", "Use text comparison for text-heavy PDFs and visual comparison for appearance changes."], keywords: ["compare","diff","changed","scanned","alignment"] },
  { id: "create", title: "Create a PDF from text, Markdown, or simple HTML", category: "Quick tools", summary: "Create PDF paginates your content locally with metric page controls and reusable style presets.", steps: ["Open Tools → Create PDF.", "Choose Markdown, plain text, or simple HTML.", "Set page size, margins, typography, header/footer, and page numbers.", "Use searchable output for normal supported scripts; use visual compatibility when browser shaping is required.", "Preview, then download or save as a project."], keywords: ["create","markdown","html","text","pdf"] },
  { id: "batch", title: "Run the same actions on multiple PDFs", category: "Advanced", summary: "Batch automation applies a reusable ordered recipe to several local PDFs.", steps: ["Open Batch automation.", "Add input PDFs.", "Add actions in the order they should run.", "Multi-output actions such as Split or Page images must remain last.", "Save/export the recipe if you want to reuse it.", "Run the queue and download individual outputs or one ZIP."], keywords: ["batch","automation","recipe","multiple"] },
  { id: "accessibility", title: "Check accessibility and document standards", category: "Advanced", summary: "Accessibility checks tags, reading order, image descriptions, form descriptions, signatures, archive readiness, and print/security findings.", steps: ["Switch the workspace to Advanced.", "Open Accessibility.", "Review plain-language findings first.", "Repair supported language/title/form-description/structure issues.", "Use technical details only when a standard or external validator requires them.", "Treat PDF/A output as a prepared candidate until independently validated."], keywords: ["accessibility","pdf/a","standards","tags","archive","signature"] },
  { id: "print-advanced", title: "Document numbering, booklet layout, and layers", category: "Advanced", summary: "Print & Advanced contains specialist production tools that most users do not need for ordinary editing.", steps: ["Switch to Advanced and open Print & Advanced.", "Document numbering (Bates) adds sequential legal/archive labels.", "Print layout / booklet arranges pages onto A4/A3 sheets.", "Layers shows or hides optional PDF layers.", "Archive check reports PDF/A-oriented risks."], keywords: ["bates","numbering","imposition","booklet","layers","archive"] },
  { id: "inspect-repair", title: "Inspect or repair a problematic PDF", category: "Troubleshooting", summary: "Inspect exposes technical PDF structure; Repair rewrites a separate clean copy when a PDF behaves unexpectedly.", steps: ["Use Repair first when a file simply will not behave correctly.", "Use Inspect only when you need technical details about fonts, forms, actions, signatures, revisions, or resources.", "Neither tool overwrites the source project."], keywords: ["inspect","repair","broken","diagnostics"] },
  { id: "what-changes", title: "Understand the What changes? panel", category: "Advanced", summary: "The optional What changes? panel explains which PDF structures an operation keeps, rebuilds, or may remove.", steps: ["Switch to Advanced.", "Choose What changes? in the document header.", "Read Preserved, Changes, and Possible losses.", "Close the panel when you no longer need technical preservation details."], keywords: ["preservation","what changes","structure","loss"] },
  { id: "backup", title: "Back up and restore a project", category: "Recovery", summary: "A .lpsproject file contains the source PDF and supported local project state with integrity checks.", steps: ["Choose Back up project from Read or Documents.", "Store the .lpsproject file outside browser storage.", "Use Restore project when needed.", "A checksum or package-consistency failure blocks restoration instead of silently trusting damaged data."], keywords: ["backup","restore","lpsproject","recovery"] },
  { id: "safe-mode", title: "Recover from repeated startup problems", category: "Troubleshooting", summary: "Safe Mode suppresses automatic project reopening and service-worker participation for the current tab.", steps: ["Open Help → Advanced & support → Troubleshooting & recovery.", "Enter Safe Mode and reload.", "Run project health or repair the offline cache if needed.", "Export a privacy-safe support bundle only when troubleshooting.", "Exit Safe Mode after the issue is resolved."], keywords: ["safe mode","crash","cache","maintenance"] }
];

export const keyboardShortcuts = [
  ["Ctrl/Cmd + K", "Open command palette"],
  ["Ctrl/Cmd + O", "Open a PDF where supported by the active workflow"],
  ["Ctrl/Cmd + S", "Save or export in supported workspaces"],
  ["Ctrl/Cmd + Z", "Undo"],
  ["Ctrl/Cmd + Shift + Z", "Redo"],
  ["Ctrl/Cmd + F", "Search the current PDF"],
  ["Delete", "Delete selected editor objects or organizer pages"],
  ["Arrow keys", "Nudge selected editor objects"],
  ["Escape", "Close dialogs, menus, or the current transient action"]
] as const;
