import { helpArticles, type HelpArticle } from "./helpContent";

export interface TaskHelpArticle extends HelpArticle { taskId?: string }
const corrections: Record<string, Partial<TaskHelpArticle>> = {
  privacy: { steps: ["Choose a PDF tool and select files from your device.", "Quick tools process files in memory; saving a project is optional. The editor saves a local project so you can return to it.", "Download the result to keep a copy outside browser storage. Your original file is not overwritten.", "The app runtime and explicitly installed OCR language packs may use the network. Your document bytes are not uploaded."] },
  "find-task": { steps: ["Open All PDF tools or press Ctrl/Cmd + K.", "Search by the action you need: crop, split, compare, fill forms, remove metadata or PDF to Word.", "Choose the matching task, then select your file. Dropping files on Home reverses these steps without requiring a second file selection.", "Within a document, Document actions opens the same task directory and prepares your current edits for the next task.", "Specialist operations remain available under More tools & troubleshooting. Read any capability warning before starting."] },
  viewer: { taskId: "read-pdf", steps: ["Choose Read PDF and select your file.", "Use the page arrows or page field to navigate and the side panel for thumbnails, outline, search or document information.", "Choose Single or Continuous view and adjust the zoom.", "Download original PDF saves the unchanged source. Back up project saves the source and supported local project state."] },
  edit: { taskId: "edit-pdf", steps: ["Choose Edit PDF and select your file.", "Choose Add text, Highlight, Image or Signature from the editing toolbar. More tools contains less-common editing actions.", "To change text already inside a PDF, choose Edit existing text instead of Add text. Not every PDF structure supports this operation.", "Select an object to adjust it in Properties. Use Undo to reverse a change.", "Download PDF creates your edited copy. Document actions can pass the current edited document to another tool."] },
  "visual-signature": { taskId: "visual-signature" },
  redaction: { taskId: "apply-redactions", steps: ["In the editor, use Mark redaction under More tools to mark sensitive regions.", "A mark is not permanent removal. Do not send the marked PDF as a redacted document.", "Open Document actions and choose Apply permanent redactions.", "Review the marked regions, capability warnings and output checks. Unsupported structures may block the operation rather than produce an unsafe result.", "Download the validated redacted copy and review it before sharing."] },
  forms: { taskId: "fill-forms", steps: ["Choose Fill PDF forms and select your PDF.", "Select a supported interactive field on the page or in the field list and enter its value.", "Review values in the page preview, then choose Download PDF.", "For a flat document without editable form fields, use Fill with text in the editor. This places text on the page; it does not create interactive fields."] },
  protect: { taskId: "password-protect", title: "Password-protect or unlock a PDF", summary: "Create a protected copy or remove a password you already know. These operations do not also flatten or sanitize the document.", steps: ["Choose Password-protect PDF and select a document.", "Enter the desired output password twice and create the protected copy.", "To remove existing protection, use Unlock PDF and enter the current password when required.", "The app checks that the output reopens before offering its download. Passwords remain in memory rather than URLs or saved settings."] },
  organize: { taskId: "organize-pages", steps: ["Choose Organize pages and select PDFs, images or a mixture of both.", "Arrange the thumbnails in the order you want the output. Drag or use the accessible move controls.", "Rotate, duplicate, remove, insert blank pages, insert files or replace a selected page. Undo restores previous choices.", "Use duplex interleaving to combine front/back scans when appropriate, and check the final order.", "Download the assembled PDF. Standard annotations, supported forms and retained-page links are copied; document-level structures and signatures require review."] },
  "page-tools": { taskId: "crop-pages", title: "Crop a page visually", summary: "Drag a crop rectangle or enter precise margins. Cropping hides content; it does not securely erase it.", steps: ["Choose Crop pages and select your PDF.", "Drag the crop handles on the preview or enter margins in millimetres.", "Choose which pages receive the crop. Reset removes your selection.", "Download the cropped copy. Use permanent redaction instead when content must be removed securely."] },
  ocr: { taskId: "ocr-pdf" }, optimize: { taskId: "compress-pdf" },
  toolbox: { taskId: "add-watermark", title: "Add a watermark or page numbers", summary: "Both actions have focused tools with page selection; they do not require a technical utilities workspace.", steps: ["Choose Add watermark or Add page numbers from All PDF tools.", "Select your PDF and choose the affected pages.", "Enter watermark text, or choose the first page number, position and text size.", "Download the new copy. Unsupported text scripts produce an explicit error rather than silently replacing characters.", "For document properties, use Remove metadata or the advanced Edit or remove metadata tool instead."] },
  merge: { taskId: "merge-pdfs", summary: "Combine PDFs and JPG, PNG or WebP images in one visual assembly workflow.", steps: ["Choose Merge PDFs or drop your files on Home and choose Merge PDFs.", "Add PDFs, images or both. Enter a source password if needed.", "Arrange the file order, or expand the page arrangement to insert, replace, rotate or remove individual pages.", "Check the exact final order and create the merged PDF.", "Download it, or continue directly into compression, protection or another supported tool."] },
  scan: { taskId: "scan-to-pdf", steps: ["Choose Scan to PDF, or drop JPG, PNG or WebP images on Home and choose Scan to PDF.", "Add images or capture pages where your browser supports the camera. PDF inputs belong in Merge PDFs instead.", "Reorder and rotate the pages. Choose OCR only when you need searchable text.", "Create and download the PDF. Cancel stops processing without publishing a partially finished result.", "Changing inputs or options invalidates the previous output, so the download cannot silently contain older settings."] },
  compare: { taskId: "compare-pdfs" }, create: { taskId: "create-pdf" }, batch: { taskId: "batch-automation" },
  accessibility: { taskId: "accessibility-check" }, "print-advanced": { taskId: "print-layout" },
  "inspect-repair": { taskId: "repair-pdf", steps: ["Choose Repair PDF and select the problem file, even if the normal preview cannot open it.", "Run repair to rebuild recoverable structure in a separate copy.", "Download is available only after the output reopens successfully. Missing or irreversibly damaged content cannot be recreated.", "Review every page before relying on the result. Document technical details provides deeper inspection under advanced tools."] },
  history: { steps: ["Open Document actions and choose History & checkpoints.", "Create a named checkpoint before a risky workflow when useful.", "Restore a checkpoint as a separate project if needed.", "Use Technical history only when troubleshooting revision or transaction details."] },
};

const added: TaskHelpArticle[] = [
  { id: "word-export", taskId: "pdf-to-docx", title: "Export a PDF to editable Word", category: "Convert & optimize", summary: "PDF to Word reconstructs editable paragraphs, common tables, qualified images, page geometry and supported styling locally. Exact PDF line wrapping and complex artwork can differ.", steps: ["Choose PDF to Word and select your PDF.", "Select the pages you want to include. Selected source pages remain separated as Word sections.", "Create and download the Word document. Qualified tables stay editable and supported image regions are embedded separately from the text.", "For scans with no selectable text, run OCR first. Review multi-column order, exact wrapping and diagram-heavy pages because PDF and Word use different layout models."], keywords: ["word", "docx", "office", "convert", "editable", "layout", "tables", "images"] },
  { id: "flatten", taskId: "flatten-pdf", title: "Flatten forms or annotations", category: "Protect & sign", summary: "Turn supported interactive content into fixed page appearance, keeping its visible values.", steps: ["Choose Flatten PDF and select your file.", "Choose forms, annotations or both. At least one option must be selected.", "Create a copy and inspect its appearance.", "Download the result. Flattened items are no longer independently editable; this is not redaction or digital signing."], keywords: ["flatten", "forms", "annotations", "static", "print"] },
  { id: "cleanup", taskId: "sanitize-pdf", title: "Remove active PDF content", category: "Protect & sign", summary: "Clean up PDF removes scripts and automatic actions, with optional attachment and metadata removal.", steps: ["Choose Clean up PDF and select your document.", "Decide whether to remove embedded attachments and metadata as well.", "Create and download the checked copy.", "This is not malware certification or removal of visible sensitive text. Use permanent redaction for sensitive page content."], keywords: ["sanitize", "cleanup", "javascript", "actions", "attachments"] },
  { id: "remove-properties", taskId: "remove-metadata", title: "Remove document metadata", category: "Document utilities", summary: "Remove document properties and catalog XMP metadata without changing visible page content.", steps: ["Choose Remove metadata and select your PDF.", "Create and download the new copy.", "Check visible content and annotations separately: removing author properties does not erase names printed on a page or stored in a comment."], keywords: ["metadata", "author", "title", "xmp", "properties", "privacy"] },
];
export const taskFirstHelpArticles: TaskHelpArticle[] = [...helpArticles.map(article => ({ ...article, ...corrections[article.id] })), ...added];
