import fs from "node:fs";
import path from "node:path";
import { expect, test } from "@playwright/test";

const top20: Array<{ prompt: string; label: string }> = [
  { prompt: "change existing text", label: "Edit PDF" },
  { prompt: "add new text", label: "Edit PDF" },
  { prompt: "replace an image", label: "Edit PDF" },
  { prompt: "highlight some text", label: "Annotate & comment" },
  { prompt: "sign this document visually", label: "Add visual signature" },
  { prompt: "permanently hide this account number", label: "Apply permanent redactions" },
  { prompt: "combine two PDFs", label: "Merge PDFs" },
  { prompt: "split this PDF into parts", label: "Split PDF" },
  { prompt: "extract pages 4 through 7", label: "Organize pages" },
  { prompt: "remove pages 4 through 7", label: "Organize pages" },
  { prompt: "move pages into a new order", label: "Organize pages" },
  { prompt: "rotate pages", label: "Organize pages" },
  { prompt: "trim page margins", label: "Crop pages" },
  { prompt: "make this PDF smaller", label: "Compress PDF" },
  { prompt: "make this scan searchable", label: "OCR PDF" },
  { prompt: "remove document metadata", label: "Edit or remove metadata" },
  { prompt: "lock this PDF with a password", label: "Password-protect PDF" },
  { prompt: "fill this form", label: "Fill PDF forms" },
  { prompt: "turn photos into a PDF", label: "Scan to PDF" },
  { prompt: "export PDF pages as images", label: "Export PDF content" }
];

test("R8 structural top-20 task discovery resolves natural-language prompts", async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== "chromium", "Search structure is browser-independent");
  await page.goto("./#/tools");
  const search = page.getByRole("searchbox", { name: "Search PDF tasks" });
  for (const item of top20) {
    await search.fill(item.prompt);
    const result = page.locator(".task-tile").filter({ hasText: item.label }).first();
    await expect(result, `Expected '${item.prompt}' to reveal '${item.label}'`).toBeVisible();
  }
});

test("R8 command palette accepts outcome phrases instead of exact menu labels", async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== "chromium", "Command search structure is browser-independent");
  await page.goto("./#/home");
  await page.keyboard.press("Control+K");
  const dialog = page.getByRole("dialog", { name: /Find a PDF task/i });
  await expect(dialog).toBeVisible();
  const search = dialog.getByRole("textbox", { name: "Search PDF tasks" });
  await search.fill("make this PDF smaller");
  await expect(dialog.getByRole("link", { name: /Compress PDF/i })).toBeVisible();
  await search.fill("permanently hide this account number");
  await expect(dialog.getByRole("link", { name: /Apply permanent redactions/i })).toBeVisible();
});

test("R8 opens a representative sample from the pinned external corpus", async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== "chromium", "External opening sample is qualified once; cross-browser coverage exists separately");
  const manifestPath = path.resolve("tests/corpus/r8-external/manifest.json");
  test.skip(!fs.existsSync(manifestPath), "R8 external corpus is generated by CI");
  const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8")) as { documents: Array<{ filename: string }> };
  const sample = manifest.documents.slice(0, 6);
  expect(sample).toHaveLength(6);

  for (const item of sample) {
    await page.goto("./#/home");
    await page.locator('input[type="file"][accept*="pdf"]').first().setInputFiles(path.resolve("tests/corpus/r8-external", item.filename));
    await expect(page.getByRole("navigation", { name: "Document workspace" })).toBeVisible({ timeout: 20_000 });
    await expect(page.locator(".viewer-page, .viewer-page-container, canvas").first()).toBeVisible({ timeout: 20_000 });
  }
});
