import { expect, test } from "@playwright/test";

const top20: Array<{ prompt: string; label: string }> = [
  { prompt: "change existing text", label: "Edit PDF" },
  { prompt: "add new text", label: "Edit PDF" },
  { prompt: "replace an image", label: "Edit PDF" },
  { prompt: "highlight some text", label: "Annotate & comment" },
  { prompt: "sign this document visually", label: "Add visual signature" },
  { prompt: "permanently hide this account number", label: "Apply permanent redactions" },
  { prompt: "combine two PDFs", label: "Merge PDFs" },
  { prompt: "split this PDF into parts", label: "Split PDF" },
  { prompt: "extract pages 4 through 7", label: "Organize pages" },
  { prompt: "remove pages 4 through 7", label: "Organize pages" },
  { prompt: "move pages into a new order", label: "Organize pages" },
  { prompt: "rotate pages", label: "Organize pages" },
  { prompt: "trim page margins", label: "Crop pages" },
  { prompt: "make this PDF smaller", label: "Compress PDF" },
  { prompt: "make this scan searchable", label: "OCR PDF" },
  { prompt: "remove document metadata", label: "Edit or remove metadata" },
  { prompt: "lock this PDF with a password", label: "Password-protect PDF" },
  { prompt: "fill this form", label: "Fill PDF forms" },
  { prompt: "turn photos into a PDF", label: "Scan to PDF" },
  { prompt: "export PDF pages as images", label: "Export PDF content" }
];

function r8ExternalCorpusEnabled(): boolean {
  const runtime = globalThis as typeof globalThis & { process?: { env?: Record<string, string | undefined> } };
  return runtime.process?.env?.R8_EXTERNAL_CORPUS === "1";
}

test("R8 structural top-20 task discovery ranks natural-language prompts correctly", async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== "chromium", "Search structure is browser-independent");
  await page.goto("./#/tools");
  const search = page.getByRole("searchbox", { name: "Search PDF tasks" });
  for (const item of top20) {
    await search.fill(item.prompt);
    const firstResult = page.locator(".task-category--search-results .task-tile").first();
    await expect(firstResult, `Expected '${item.prompt}' to rank '${item.label}' first`).toBeVisible();
    await expect(firstResult).toContainText(item.label);
  }
});

test("R8 command palette ranks outcome phrases instead of exact menu labels", async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== "chromium", "Command search structure is browser-independent");
  await page.goto("./#/home");
  const trigger = page.getByRole("button", { name: "Open command palette" });
  await expect(trigger).toBeVisible();
  await trigger.focus();
  await page.keyboard.press("Control+K");
  const dialog = page.getByRole("dialog", { name: /Find a PDF task/i });
  await expect(dialog).toBeVisible({ timeout: 10_000 });
  const search = dialog.getByRole("textbox", { name: "Search PDF tasks" });
  const firstResult = dialog.locator(".command-palette__results a").first();
  await search.fill("make this PDF smaller");
  await expect(firstResult).toContainText("Compress PDF");
  await search.fill("permanently hide this account number");
  await expect(firstResult).toContainText("Apply permanent redactions");
});

test("R8 opens a representative sample from the pinned external corpus", async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== "chromium", "External opening sample is qualified once; cross-browser coverage exists separately");
  test.skip(!r8ExternalCorpusEnabled(), "R8 external corpus is generated by the release CI job");

  for (let index = 1; index <= 6; index += 1) {
    const filename = `${String(index).padStart(2, "0")}.pdf`;
    await page.goto("./#/home");
    await page.locator('input[type="file"][accept*="pdf"]').first().setInputFiles(`tests/corpus/r8-external/${filename}`);
    await expect(page.getByRole("navigation", { name: "Document workspace" })).toBeVisible({ timeout: 20_000 });
    await expect(page.getByRole("region", { name: "PDF page 1", exact: true })).toBeVisible({ timeout: 20_000 });
  }
});
