import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, mkdir, writeFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { channels, projects, summarizeReport, certifyMatrix, loadReleaseContractIdentity } from "./certify-browser-matrix.mjs";

function report(project = "chromium") {
  return { errors: [], stats: {expected:1,skipped:0,unexpected:0,flaky:0}, suites: [{specs:[{
    title:"real PDF output", tests:[{projectName:project,status:"expected",expectedStatus:"passed",results:[{status:"passed",retry:0,errors:[]}]}]
  }]}] };
}
const testCase = report => report.suites[0].specs[0].tests[0];
describe("release-certificate boundaries", () => {
  it("accepts an executed passing report", () => assert.equal(summarizeReport(report(), "chromium").passed, 1));
  it("rejects no-tests and global errors", () => {
    assert.throws(() => summarizeReport({suites:[]}, "chromium"));
    const input=report(); input.errors.push({message:"browser unavailable"});
    assert.throws(() => summarizeReport(input, "chromium"));
  });
  it("rejects failed, flaky, retried and expected-failure cases", () => {
    for (const status of ["unexpected", "flaky"]) {
      const input=report(); testCase(input).status=status;
      assert.throws(() => summarizeReport(input, "chromium"));
    }
    const retry=report(); testCase(retry).results.push({status:"passed",retry:1,errors:[]});
    assert.throws(() => summarizeReport(retry,"chromium"));
    const failed=report(); testCase(failed).expectedStatus="failed";
    assert.throws(() => summarizeReport(failed,"chromium"));
  });
  it("rejects a mismatched project or fabricated count", () => {
    assert.throws(() => summarizeReport(report(),"firefox"));
    const input=report(); input.stats.expected=100;
    assert.throws(() => summarizeReport(input,"chromium"));
  });
  it("records explained capability skips but refuses disabled external-corpus coverage", () => {
    const input=report(); const skipped=structuredClone(testCase(input));
    skipped.status="skipped"; skipped.results=[{status:"skipped",retry:0}];
    skipped.annotations=[{type:"skip",description:"Timing APIs are Chromium-only."}];
    input.suites[0].specs[0].tests.push(skipped); input.stats.skipped=1;
    assert.equal(summarizeReport(input,"chromium").skipped,1);
    skipped.annotations[0].description="R8 external corpus is generated by the release CI job";
    assert.throws(() => summarizeReport(input,"chromium"));
    skipped.annotations=[]; assert.throws(() => summarizeReport(input,"chromium"));
  });
  it("binds certificate identity to the frozen roadmap and curated notes", async () => {
    const identity = await loadReleaseContractIdentity();
    assert.equal(identity.version, "7.1.4");
    assert.equal(identity.roadmap, "task-first-product-hardening");
    assert.equal(identity.stableTag, "v7.1.4");
    assert.equal(identity.projectPackageVersion, 9);
    assert.equal(identity.databaseSchemaVersion, 13);
    assert.match(identity.freezeSha256, /^[a-f0-9]{64}$/);
    assert.match(identity.releaseNotesSha256, /^[a-f0-9]{64}$/);
    assert.equal(identity.releaseNotesPath, "docs/releases/v7.1.4/release-notes.md");
  });
  it("requires all ten channel/project reports and rejects missing or duplicate reports", async () => {
    const directory=await mkdtemp(join(tmpdir(),"pdf-matrix-"));
    const identity={sourceSha:"a".repeat(40),version:"7.1.4"};
    try {
      await assert.rejects(() => certifyMatrix(directory,identity));
      for (const channel of channels) for (const project of projects) {
        const dir=join(directory,`pdf-browser-${channel}-${project}`); await mkdir(dir);
        await writeFile(join(dir,"browser-results.json"),JSON.stringify(report(project)));
      }
      const certificate=await certifyMatrix(directory,identity);
      assert.equal(certificate.matrix.length,10); assert.equal(certificate.totals.passed,10);
      const duplicate=join(directory,"pdf-browser-stable-webkit","duplicate"); await mkdir(duplicate);
      await writeFile(join(duplicate,"browser-results.json"),JSON.stringify(report("webkit")));
      await assert.rejects(() => certifyMatrix(directory,identity));
      await assert.rejects(() => certifyMatrix(directory,{sourceSha:"main"}));
    } finally { await rm(directory,{recursive:true,force:true}); }
  });
});
