import { useEffect, useRef, useState } from "react";
import { listBatchRecipes, saveBatchRecipe } from "../processing/batchRepository";
import { batchStepLabel, defaultBatchStep, runBatchRecipe } from "../processing/batchPipeline";
import { parseBatchRecipeJson, serializeBatchRecipe } from "../processing/batchModel";
import { downloadBlob } from "../projects/download";
import { BATCH_RECIPE_SCHEMA_VERSION, type BatchItemStatus, type BatchRecipe, type BatchStep } from "../types/batch";
import { createStoredZip } from "../toolbox/zip";

interface BatchItem { id: string; file: File; status: BatchItemStatus; progress: number; message: string; output?: Uint8Array; outputFilename?: string; outputMime?: string; error?: string }
const DEFAULT_RECIPE: BatchRecipe = { schemaVersion: BATCH_RECIPE_SCHEMA_VERSION, id: "current", name: "Document cleanup", steps: [{ id: "optimize-default", type: "optimize" }], outputSuffix: "processed", updatedAt: Date.now() };
const STEP_TYPES: Array<{type:BatchStep["type"];label:string}> = [
  {type:"rotate",label:"Rotate pages"},{type:"optimize",label:"Lossless optimize"},{type:"remove-metadata",label:"Remove metadata"},{type:"crop",label:"Crop margins"},{type:"decorate",label:"Watermark / numbering"},{type:"blank-pages",label:"Insert blank pages"},{type:"raster-compress",label:"Raster compress"},{type:"grayscale",label:"Grayscale PDF"},{type:"split-fixed",label:"Split into PDF parts"},{type:"page-images",label:"Export page images"}
];

export function BatchPage() {
  const inputRef=useRef<HTMLInputElement|null>(null),recipeInputRef=useRef<HTMLInputElement|null>(null),abortRef=useRef<AbortController|null>(null),pauseRef=useRef(false);
  const [items,setItems]=useState<BatchItem[]>([]),[recipe,setRecipe]=useState<BatchRecipe>(DEFAULT_RECIPE),[recipes,setRecipes]=useState<BatchRecipe[]>([]);
  const [running,setRunning]=useState(false),[paused,setPaused]=useState(false),[error,setError]=useState<string|null>(null),[newStepType,setNewStepType]=useState<BatchStep["type"]>("rotate");
  const recipeLocked = running || paused;
  useEffect(()=>{void listBatchRecipes().then(setRecipes);},[]);
  function addFiles(files:FileList|File[]){setItems(current=>[...current,...[...files].filter(file=>file.type==="application/pdf"||file.name.toLowerCase().endsWith(".pdf")).map(file=>({id:crypto.randomUUID(),file,status:"pending" as const,progress:0,message:"Queued"}))]);}
  function patch(id:string,value:Partial<BatchItem>){setItems(current=>current.map(item=>item.id===id?{...item,...value}:item));}
  function patchStep(id:string,value:Partial<BatchStep>){setRecipe(current=>({...current,steps:current.steps.map(step=>step.id===id?{...step,...value} as BatchStep:step)}));}
  const isTerminalStep=(step:BatchStep)=>step.type==="split-fixed"||step.type==="page-images";
  function appendStep(type:BatchStep["type"]){setRecipe(current=>{const next=defaultBatchStep(type);if(isTerminalStep(next))return{...current,steps:[...current.steps.filter(step=>!isTerminalStep(step)),next]};const terminalIndex=current.steps.findIndex(isTerminalStep);if(terminalIndex<0)return{...current,steps:[...current.steps,next]};const steps=[...current.steps];steps.splice(terminalIndex,0,next);return{...current,steps};});}
  function moveStep(index:number,direction:-1|1){setRecipe(current=>{const steps=[...current.steps],target=index+direction;if(target<0||target>=steps.length)return current;const moving=steps[index],other=steps[target];if(isTerminalStep(moving)&&target!==steps.length-1)return current;if(isTerminalStep(other)&&direction===1)return current;[steps[index],steps[target]]=[steps[target],steps[index]];return {...current,steps};});}
  async function run(){if(!recipe.steps.length){setError("Add at least one recipe step.");return;} if(!items.some(item=>item.status==="pending"||item.status==="failed"||item.status==="cancelled"))return;const recipeSnapshot=structuredClone(recipe);setRunning(true);setPaused(false);setError(null);pauseRef.current=false;
    for(const item of items){if(pauseRef.current){setPaused(true);break;}if(!["pending","failed","cancelled"].includes(item.status))continue;const controller=new AbortController();abortRef.current=controller;patch(item.id,{status:"running",progress:.01,message:"Opening…",error:undefined});try{const source=new Uint8Array(await item.file.arrayBuffer());const artifact=await runBatchRecipe(source,recipeSnapshot,controller.signal,(progress,message)=>patch(item.id,{progress:Math.max(.01,Math.min(.98,progress)),message}));const outputFilename=`${item.file.name.replace(/\.pdf$/i,"")}-${recipeSnapshot.outputSuffix||"processed"}${artifact.extension}`;patch(item.id,{status:"complete",progress:1,message:`${(artifact.bytes.byteLength/1_000_000).toFixed(2)} MB · ${artifact.kind}`,output:artifact.bytes,outputFilename,outputMime:artifact.mimeType});}catch(reason){const cancelled=reason instanceof DOMException&&reason.name==="AbortError";patch(item.id,{status:cancelled?"cancelled":"failed",message:cancelled?"Cancelled":"Failed",error:cancelled?undefined:reason instanceof Error?reason.message:String(reason)});}}
    abortRef.current=null;setRunning(false);
  }
  async function saveRecipe(){const saved={...recipe,id:recipe.id==="current"?crypto.randomUUID():recipe.id,updatedAt:Date.now()};await saveBatchRecipe(saved);setRecipe(saved);setRecipes(await listBatchRecipes());}
  function exportRecipe(){const blob=new Blob([serializeBatchRecipe(recipe)],{type:"application/json;charset=utf-8"});downloadBlob(blob,`${(recipe.name||"batch-recipe").replace(/[^a-zA-Z0-9_-]+/g,"-").replace(/^-+|-+$/g,"")||"batch-recipe"}.lpsrecipe.json`);}
  async function importRecipe(file:File){setError(null);try{const imported=parseBatchRecipeJson(await file.text());setRecipe(imported);await saveBatchRecipe(imported);setRecipes(await listBatchRecipes());}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}}
  function downloadAll(){const outputs=items.filter((item):item is BatchItem & {output:Uint8Array}=>Boolean(item.output));if(!outputs.length)return;const zip=createStoredZip(outputs.map((item,index)=>({name:`${String(index+1).padStart(3,"0")}-${item.outputFilename||`${item.file.name.replace(/\.pdf$/i,"")}-processed.pdf`}`,bytes:item.output})));downloadBlob(new Blob([Uint8Array.from(zip).buffer],{type:"application/zip"}),"batch-outputs.zip");} 
  return <div className="batch-page"><section className="tools-hero"><p className="eyebrow">Batch automation</p><h2>Apply the same saved actions to multiple PDFs.</h2><p>Choose actions in order, add several PDFs, and run the same workflow on all of them. Split and Page images can produce ZIP output and must remain last.</p></section>{error?<div className="error-banner"><strong>Batch issue</strong><span>{error}</span></div>:null}<div className="batch-layout"><aside className="batch-recipe"><h3>Recipe</h3><label>Name<input disabled={recipeLocked} value={recipe.name} onChange={event=>setRecipe({...recipe,name:event.target.value})}/></label>
    <div className="batch-step-add"><select disabled={recipeLocked} value={newStepType} onChange={event=>setNewStepType(event.target.value as BatchStep["type"])}>{STEP_TYPES.map(item=><option key={item.type} value={item.type}>{item.label}</option>)}</select><button className="button button--small" disabled={recipeLocked} onClick={()=>appendStep(newStepType)} type="button">Add step</button></div>
    <div className="batch-steps">{recipe.steps.map((step,index)=><article className="batch-step" key={step.id}><header><strong>{index+1}. {batchStepLabel(step)}</strong><div><button disabled={recipeLocked||index===0} onClick={()=>moveStep(index,-1)} type="button">↑</button><button disabled={recipeLocked||index===recipe.steps.length-1} onClick={()=>moveStep(index,1)} type="button">↓</button><button disabled={recipeLocked} onClick={()=>setRecipe(current=>({...current,steps:current.steps.filter(item=>item.id!==step.id)}))} type="button">×</button></div></header><StepEditor step={step} disabled={recipeLocked} patch={value=>patchStep(step.id,value)}/></article>)}</div>
    {!recipe.steps.length?<p className="muted">No steps. Add one above.</p>:null}<label>Output suffix<input disabled={recipeLocked} value={recipe.outputSuffix} onChange={event=>setRecipe({...recipe,outputSuffix:event.target.value.replace(/[^a-zA-Z0-9_-]/g,"")})}/></label><div className="batch-recipe-actions"><button className="button button--secondary" disabled={recipeLocked||!recipe.steps.length} onClick={()=>void saveRecipe()} type="button">Save recipe</button><button className="button button--ghost" disabled={recipeLocked||!recipe.steps.length} onClick={exportRecipe} type="button">Export JSON</button><button className="button button--ghost" disabled={recipeLocked} onClick={()=>recipeInputRef.current?.click()} type="button">Import JSON</button><input ref={recipeInputRef} hidden accept="application/json,.json" type="file" onChange={event=>{const file=event.target.files?.[0];if(file)void importRecipe(file);event.target.value="";}}/></div>{recipes.length?<label>Saved recipes<select disabled={recipeLocked} value={recipes.some(entry=>entry.id===recipe.id)?recipe.id:""} onChange={event=>{const selected=recipes.find(entry=>entry.id===event.target.value);if(selected)setRecipe(selected);}}><option value="">Select…</option>{recipes.map(entry=><option key={entry.id} value={entry.id}>{entry.name}</option>)}</select></label>:null}
  </aside><main className="batch-queue"><div className="batch-toolbar"><button className="button" disabled={running} onClick={()=>inputRef.current?.click()} type="button">Add PDFs</button><input ref={inputRef} accept="application/pdf,.pdf" hidden multiple type="file" onChange={event=>{if(event.target.files)addFiles(event.target.files);event.target.value="";}}/><button className="button button--secondary" disabled={running||!items.length} onClick={()=>{setItems([]);setPaused(false);pauseRef.current=false;}} type="button">Clear</button><button className="button button--secondary" disabled={running||!items.some(item=>item.output)} onClick={downloadAll} type="button">Download all ZIP</button><span>{items.length} file(s)</span></div><div className="batch-items">{items.map(item=><article className={`batch-item batch-item--${item.status}`} key={item.id}><div><strong>{item.file.name}</strong><span>{(item.file.size/1_000_000).toFixed(2)} MB</span></div><div><span>{item.message}</span><progress max="1" value={item.progress}/></div>{item.error?<p>{item.error}</p>:null}<div className="batch-item__actions">{item.output?<button className="button button--tiny" onClick={()=>downloadBlob(new Blob([Uint8Array.from(item.output!).buffer],{type:item.outputMime||"application/pdf"}),item.outputFilename || `${item.file.name.replace(/\.pdf$/i,"")}-processed.pdf`)} type="button">Download</button>:null}<button className="button button--tiny button--ghost" disabled={running&&item.status==="running"} onClick={()=>setItems(current=>current.filter(entry=>entry.id!==item.id))} type="button">Remove</button></div></article>)}</div>{!items.length?<div className="empty-state"><strong>No queued PDFs</strong><p>Add files, build a recipe, then run the queue.</p></div>:null}<footer className="batch-runbar"><button className="button" disabled={running||!items.length||!recipe.steps.length} onClick={()=>void run()} type="button">{paused?"Resume queue":"Run queue"}</button>{paused&&!running?<button className="button button--secondary" onClick={()=>setPaused(false)} type="button">End paused run</button>:null}{running?<><button className="button button--secondary" onClick={()=>{pauseRef.current=true;}} type="button">Pause after current</button><button className="button button--ghost" onClick={()=>abortRef.current?.abort()} type="button">Cancel current</button></>:null}</footer></main></div></div>;
}

function StepEditor({step,disabled,patch}:{step:BatchStep;disabled:boolean;patch:(value:Partial<BatchStep>)=>void}){
  if(step.type==="rotate")return <label>Degrees<select disabled={disabled} value={step.degrees} onChange={event=>patch({degrees:Number(event.target.value) as 90|180|270})}><option value="90">90°</option><option value="180">180°</option><option value="270">270°</option></select></label>;
  if(step.type==="crop")return <div className="batch-step-grid">{(["topMm","rightMm","bottomMm","leftMm"] as const).map(key=><label key={key}>{key.replace("Mm","")} (mm)<input disabled={disabled} min="0" type="number" value={step[key]} onChange={event=>patch({[key]:Math.max(0,Number(event.target.value))} as Partial<BatchStep>)}/></label>)}</div>;
  if(step.type==="decorate")return <div className="batch-step-grid"><label>Watermark<input disabled={disabled} value={step.watermarkText} onChange={event=>patch({watermarkText:event.target.value})}/></label><label>Header<input disabled={disabled} value={step.headerText} onChange={event=>patch({headerText:event.target.value})}/></label><label>Footer<input disabled={disabled} value={step.footerText} onChange={event=>patch({footerText:event.target.value})}/></label><label className="check-row"><input disabled={disabled} checked={step.pageNumbers} type="checkbox" onChange={event=>patch({pageNumbers:event.target.checked})}/> Page numbers</label><label>Start<input disabled={disabled} type="number" value={step.startNumber} onChange={event=>patch({startNumber:Number(event.target.value)})}/></label><label>Script<select disabled={disabled} value={step.fontLanguage ?? "auto"} onChange={event=>patch({fontLanguage:event.target.value as "auto"|"ko"|"ja"|"zh-Hans"|"zh-Hant"})}><option value="auto">Auto</option><option value="ko">Korean</option><option value="ja">Japanese</option><option value="zh-Hans">Chinese · Simplified</option><option value="zh-Hant">Chinese · Traditional</option></select></label></div>;
  if(step.type==="blank-pages")return <div className="batch-step-grid"><label>Position<select disabled={disabled} value={step.position} onChange={event=>patch({position:event.target.value as "start"|"end"})}><option value="start">Start</option><option value="end">End</option></select></label><label>Count<input disabled={disabled} min="1" max="20" type="number" value={step.count} onChange={event=>patch({count:Number(event.target.value)})}/></label><label>Width (mm)<input disabled={disabled} min="25" type="number" value={step.widthMm} onChange={event=>patch({widthMm:Number(event.target.value)})}/></label><label>Height (mm)<input disabled={disabled} min="25" type="number" value={step.heightMm} onChange={event=>patch({heightMm:Number(event.target.value)})}/></label></div>;
  if(step.type==="raster-compress")return <label>Profile<select disabled={disabled} value={step.profile} onChange={event=>patch({profile:event.target.value as "screen"|"balanced"|"small"|"print"} as Partial<BatchStep>)}><option value="screen">Screen</option><option value="balanced">Balanced</option><option value="small">Small</option><option value="print">Print</option></select></label>;
  if(step.type==="grayscale")return <label>Profile<select disabled={disabled} value={step.profile} onChange={event=>patch({profile:event.target.value as "screen"|"balanced"|"print"} as Partial<BatchStep>)}><option value="screen">Screen</option><option value="balanced">Balanced</option><option value="print">Print</option></select><small>Rasterizes pages and removes interactive PDF structure.</small></label>;
  if(step.type==="split-fixed")return <label>Pages per PDF<input disabled={disabled} min="1" max="500" type="number" value={step.pagesPerFile} onChange={event=>patch({pagesPerFile:Math.max(1,Math.min(500,Math.round(Number(event.target.value))))} as Partial<BatchStep>)}/><small>Terminal step · produces a ZIP of PDF parts.</small></label>;
  if(step.type==="page-images")return <label>Image quality<select disabled={disabled} value={step.quality} onChange={event=>patch({quality:event.target.value as "compact"|"balanced"|"high"} as Partial<BatchStep>)}><option value="compact">Compact</option><option value="balanced">Balanced</option><option value="high">High</option></select><small>Terminal step · produces a ZIP of PNG pages.</small></label>;
  return <p className="muted">No additional settings.</p>;
}
