import { useEffect, useRef, useState } from "react";
import type { PDFDocumentProxy } from "pdfjs-dist";
import { extractPageText, openPdfWithPdfJs } from "../engines/pdfjs";
import { alignPageFingerprints, type PageAlignmentRow, type PageHybridFingerprint } from "../comparison/alignment";
import { visualFingerprintFromRgba } from "../comparison/visualFingerprint";
import { diffWords, type DiffToken } from "../comparison/diff";

interface Loaded { file: File; document: PDFDocumentProxy }
async function renderPage(document:PDFDocumentProxy,pageNumber:number,scale=1):Promise<HTMLCanvasElement>{if(pageNumber<1||pageNumber>document.numPages)throw new Error(`Page ${pageNumber} does not exist in this document.`);const page=await document.getPage(pageNumber);try{const viewport=page.getViewport({scale});const canvas=window.document.createElement("canvas");canvas.width=Math.round(viewport.width);canvas.height=Math.round(viewport.height);const context=canvas.getContext("2d",{alpha:false});if(!context)throw new Error("Canvas unavailable.");context.fillStyle="#fff";context.fillRect(0,0,canvas.width,canvas.height);await page.render({canvas,canvasContext:context,viewport}).promise;return canvas;}finally{page.cleanup();}}
function blankCanvasLike(reference:HTMLCanvasElement|null):HTMLCanvasElement{const canvas=window.document.createElement("canvas");canvas.width=reference?.width??612;canvas.height=reference?.height??792;const context=canvas.getContext("2d",{alpha:false});if(!context)throw new Error("Canvas unavailable.");context.fillStyle="#fff";context.fillRect(0,0,canvas.width,canvas.height);return canvas;}
function diffCanvases(left:HTMLCanvasElement,right:HTMLCanvasElement):{canvas:HTMLCanvasElement;changedRatio:number}{const width=Math.max(left.width,right.width),height=Math.max(left.height,right.height),a=document.createElement("canvas"),b=document.createElement("canvas"),out=document.createElement("canvas");for(const canvas of[a,b,out]){canvas.width=width;canvas.height=height;}const ac=a.getContext("2d",{willReadFrequently:true})!,bc=b.getContext("2d",{willReadFrequently:true})!,oc=out.getContext("2d")!;ac.fillStyle="#fff";ac.fillRect(0,0,width,height);ac.drawImage(left,0,0);bc.fillStyle="#fff";bc.fillRect(0,0,width,height);bc.drawImage(right,0,0);const ai=ac.getImageData(0,0,width,height),bi=bc.getImageData(0,0,width,height),oi=oc.createImageData(width,height);let changed=0;for(let i=0;i<ai.data.length;i+=4){const d=Math.abs(ai.data[i]-bi.data[i])+Math.abs(ai.data[i+1]-bi.data[i+1])+Math.abs(ai.data[i+2]-bi.data[i+2]);if(d>45){changed++;oi.data[i]=220;oi.data[i+1]=50;oi.data[i+2]=50;oi.data[i+3]=Math.min(255,80+d/3);}else{oi.data[i]=245;oi.data[i+1]=245;oi.data[i+2]=245;oi.data[i+3]=80;}}oc.putImageData(oi,0,0);return{canvas:out,changedRatio:changed/(width*height)};}
async function extractAllFingerprints(document:PDFDocumentProxy,onProgress?:(done:number,total:number)=>void):Promise<PageHybridFingerprint[]>{const fingerprints:PageHybridFingerprint[]=[];for(let page=1;page<=document.numPages;page++){const text=await extractPageText(document,page);let visual; if(text.trim().replace(/\s+/g," ").length<80){const rendered=await renderPage(document,page,.18);const context=rendered.getContext("2d",{willReadFrequently:true});if(context){const image=context.getImageData(0,0,rendered.width,rendered.height);visual=visualFingerprintFromRgba(image.data,rendered.width,rendered.height);}rendered.width=1;rendered.height=1;}fingerprints.push({text,visual});onProgress?.(page,document.numPages);}return fingerprints;}

export function ComparePage(){
  const leftRef=useRef<HTMLInputElement|null>(null),rightRef=useRef<HTMLInputElement|null>(null),documentsRef=useRef<{left:PDFDocumentProxy|null;right:PDFDocumentProxy|null}>({left:null,right:null}),leftCanvas=useRef<HTMLDivElement|null>(null),rightCanvas=useRef<HTMLDivElement|null>(null),diffCanvas=useRef<HTMLDivElement|null>(null);
  const [left,setLeft]=useState<Loaded|null>(null),[right,setRight]=useState<Loaded|null>(null),[leftPage,setLeftPage]=useState<number|null>(1),[rightPage,setRightPage]=useState<number|null>(1),[mode,setMode]=useState<"visual"|"text">("visual"),[tokens,setTokens]=useState<DiffToken[]>([]),[changed,setChanged]=useState<number|null>(null),[busy,setBusy]=useState(false),[analysisProgress,setAnalysisProgress]=useState(""),[alignment,setAlignment]=useState<PageAlignmentRow[]>([]),[error,setError]=useState<string|null>(null);
  useEffect(()=>()=>{void documentsRef.current.left?.destroy();void documentsRef.current.right?.destroy();},[]);
  async function load(file:File,side:"left"|"right"){setError(null);setAlignment([]);try{const pdf=await openPdfWithPdfJs(new Uint8Array(await file.arrayBuffer()));if(side==="left"){if(documentsRef.current.left)await documentsRef.current.left.destroy();documentsRef.current.left=pdf;setLeft({file,document:pdf});setLeftPage(1);}else{if(documentsRef.current.right)await documentsRef.current.right.destroy();documentsRef.current.right=pdf;setRight({file,document:pdf});setRightPage(1);}}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}}
  async function compare(pair={leftPage,rightPage}){if(!left||!right)return;setBusy(true);setError(null);try{if(mode==="text"){const[a,b]=await Promise.all([pair.leftPage?extractPageText(left.document,pair.leftPage):Promise.resolve(""),pair.rightPage?extractPageText(right.document,pair.rightPage):Promise.resolve("")]);setTokens(diffWords(a,b,1200));setChanged(null);}else{const[leftRendered,rightRendered]=await Promise.all([pair.leftPage?renderPage(left.document,pair.leftPage,1):Promise.resolve(null),pair.rightPage?renderPage(right.document,pair.rightPage,1):Promise.resolve(null)]);const a=leftRendered??blankCanvasLike(rightRendered),b=rightRendered??blankCanvasLike(leftRendered),diff=diffCanvases(a,b);leftCanvas.current?.replaceChildren(a);rightCanvas.current?.replaceChildren(b);diffCanvas.current?.replaceChildren(diff.canvas);setChanged(diff.changedRatio);setTokens([]);}}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}finally{setBusy(false);}}
  async function analyze(){if(!left||!right)return;setBusy(true);setError(null);setAnalysisProgress("Fingerprinting original pages…");try{const leftPrints=await extractAllFingerprints(left.document,(done,total)=>setAnalysisProgress(`Original ${done}/${total}`));setAnalysisProgress("Fingerprinting revised pages…");const rightPrints=await extractAllFingerprints(right.document,(done,total)=>setAnalysisProgress(`Revised ${done}/${total}`));setAnalysisProgress("Aligning text and visual page sequence…");const rows=alignPageFingerprints(leftPrints,rightPrints);setAlignment(rows);const firstChanged=rows.find(row=>row.status!=="same")??rows[0];if(firstChanged){setLeftPage(firstChanged.leftPage);setRightPage(firstChanged.rightPage);}setAnalysisProgress("");}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}finally{setBusy(false);}}
  const chooseRow=(row:PageAlignmentRow)=>{setLeftPage(row.leftPage);setRightPage(row.rightPage);void compare({leftPage:row.leftPage,rightPage:row.rightPage});};
  return <div className="compare-page"><section className="tools-hero"><p className="eyebrow">Compare PDFs</p><h2>Compare text PDFs and scanned documents page by page.</h2><p>Pages are matched automatically, including scanned pages, so inserted or deleted pages do not throw off the rest of the comparison. Nothing leaves the browser.</p></section>{error?<div className="error-banner"><strong>Comparison issue</strong><span>{error}</span></div>:null}
    <div className="compare-inputs"><button className="file-slot" onClick={()=>leftRef.current?.click()} type="button"><strong>{left?.file.name??"Choose original PDF"}</strong><span>{left?`${left.document.numPages} pages`:"Left document"}</span></button><button className="file-slot" onClick={()=>rightRef.current?.click()} type="button"><strong>{right?.file.name??"Choose revised PDF"}</strong><span>{right?`${right.document.numPages} pages`:"Right document"}</span></button><input ref={leftRef} accept="application/pdf,.pdf" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void load(f,"left");e.target.value="";}} type="file"/><input ref={rightRef} accept="application/pdf,.pdf" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void load(f,"right");e.target.value="";}} type="file"/></div>
    <div className="compare-toolbar"><label>Mode<select onChange={e=>setMode(e.target.value as typeof mode)} value={mode}><option value="visual">Visual pixels</option><option value="text">Extracted text</option></select></label><label>Original page<input max={left?.document.numPages??1} min="1" disabled={leftPage===null} onChange={e=>setLeftPage(Math.max(1,Math.min(left?.document.numPages??1,Number(e.target.value))))} type="number" value={leftPage??""}/></label><label>Revised page<input max={right?.document.numPages??1} min="1" disabled={rightPage===null} onChange={e=>setRightPage(Math.max(1,Math.min(right?.document.numPages??1,Number(e.target.value))))} type="number" value={rightPage??""}/></label><button className="button" disabled={!left||!right||busy} onClick={()=>void compare()} type="button">{busy&&!analysisProgress?"Comparing…":"Compare pair"}</button><button className="button button--secondary" disabled={!left||!right||busy} onClick={()=>void analyze()} type="button">{analysisProgress||"Analyze document"}</button>{changed!==null?<strong>{(changed*100).toFixed(2)}% changed pixels</strong>:null}</div>
    {alignment.length?<section className="compare-alignment"><div className="section-heading"><div><p className="eyebrow">Page map</p><h3>{alignment.filter(row=>row.status!=="same").length} changed sequence row(s)</h3></div></div><div className="compare-alignment__list">{alignment.map((row,index)=><button className={`compare-alignment__row compare-alignment__row--${row.status}`} key={`${row.leftPage??"x"}-${row.rightPage??"x"}-${index}`} onClick={()=>chooseRow(row)} type="button"><span>{row.leftPage?`Original ${row.leftPage}`:"—"}</span><strong>{row.status}</strong><span>{row.rightPage?`Revised ${row.rightPage}`:"—"}</span><small>{row.leftPage&&row.rightPage?`${Math.round(row.similarity*100)}%${row.basis?` · ${row.basis}`:""} similarity`:"sequence change"}</small></button>)}</div></section>:null}
    {mode==="visual"?<div className="visual-compare-grid"><section><h3>Original{leftPage===null?" · page missing":leftPage?` · page ${leftPage}`:""}</h3><div className="compare-canvas" ref={leftCanvas}/></section><section><h3>Revised{rightPage===null?" · page missing":rightPage?` · page ${rightPage}`:""}</h3><div className="compare-canvas" ref={rightCanvas}/></section><section><h3>Difference</h3><div className="compare-canvas" ref={diffCanvas}/></section></div>:<div className="text-diff">{tokens.length?tokens.map((token,index)=><span className={`diff-${token.kind}`} key={`${index}-${token.text}`}>{token.text}</span>):<div className="empty-state"><strong>No text comparison yet</strong><p>Choose both PDFs, optionally analyze their page alignment, then compare a selected pair.</p></div>}</div>}
  </div>;
}
