import { useMemo, useRef, useState } from "react";
import { navigateTo } from "../core/appRouter";
import { buildSearchablePdf } from "../creator/creatorClient";
import { inspectPdfBytes } from "../engines/pdfjs";
import { htmlToCreatorBlocks } from "../creator/htmlImport";
import { layoutCreatorDocument } from "../creator/layout";
import { parseMarkdownBlocks, parsePlainTextBlocks } from "../creator/markdown";
import { BUILTIN_CREATOR_PRESETS, DEFAULT_CREATOR_STYLE, deleteCreatorPreset, listCreatorPresets, saveCreatorPreset } from "../creator/presets";
import { buildVisualCreatorPdf } from "../creator/rasterPdf";
import { downloadBlob } from "../projects/download";
import { createProjectFromBytes } from "../projects/projectRepository";
import type { CreatorBlock, CreatorDocumentMetadata, CreatorInlineRun, CreatorInputMode, CreatorPdfMode, CreatorPreset, CreatorStyle } from "../types/creator";

const SAMPLE=`# PDF Studio\n\nCreate a clean PDF directly from **Markdown** without uploading the document.\n\n## What this studio supports\n\n- Headings and paragraphs\n- Bulleted and numbered lists\n- Blockquotes\n- Code blocks\n- Horizontal rules\n\n> Searchable mode keeps supported text as PDF text. Visual compatibility mode uses browser shaping for maximum script compatibility.\n\n\`\`\`text\nEverything stays on this device.\n\`\`\``;
function filename(value:string):string{return(value.trim()||"created-document").replace(/[<>:"/\\|?*\x00-\x1f]/g,"-").replace(/\s+/g," ").slice(0,100)+".pdf";}
function parseBlocks(mode:CreatorInputMode,value:string):CreatorBlock[]{if(mode==="html")return htmlToCreatorBlocks(value);if(mode==="text")return parsePlainTextBlocks(value);return parseMarkdownBlocks(value);}

export function CreatePdfPage(){
  const fileRef=useRef<HTMLInputElement|null>(null),abortRef=useRef<AbortController|null>(null);
  const [mode,setMode]=useState<CreatorInputMode>("markdown"),[source,setSource]=useState(SAMPLE),[style,setStyle]=useState<CreatorStyle>({...DEFAULT_CREATOR_STYLE}),[metadata,setMetadata]=useState<CreatorDocumentMetadata>({title:"Created document",author:"",subject:"",keywords:""}),[pdfMode,setPdfMode]=useState<CreatorPdfMode>("searchable"),[presets,setPresets]=useState<CreatorPreset[]>(()=>listCreatorPresets()),[presetId,setPresetId]=useState("builtin-minimal"),[presetName,setPresetName]=useState("My preset"),[busy,setBusy]=useState(false),[progress,setProgress]=useState(""),[error,setError]=useState<string|null>(null),[output,setOutput]=useState<Uint8Array|null>(null),[warnings,setWarnings]=useState<string[]>([]);
  const blocks=useMemo(()=>parseBlocks(mode,source),[mode,source]);const layout=useMemo(()=>layoutCreatorDocument(blocks,style),[blocks,style]);
  function invalidate(){setOutput(null);setWarnings([]);setError(null);}
  function changeStyle(patch:Partial<CreatorStyle>){setStyle(current=>({...current,...patch}));invalidate();}
  function loadPreset(id:string){const preset=presets.find(item=>item.id===id);if(!preset)return;setPresetId(id);setStyle(structuredClone(preset.style));invalidate();}
  async function importSource(file:File){const text=await file.text();const lower=file.name.toLowerCase();const nextMode:CreatorInputMode=lower.endsWith(".html")||lower.endsWith(".htm")?"html":lower.endsWith(".txt")?"text":"markdown";setMode(nextMode);setSource(text);if(metadata.title==="Created document")setMetadata(current=>({...current,title:file.name.replace(/\.[^.]+$/," ").trim()||"Created document"}));invalidate();}
  async function generate(){if(!blocks.length){setError("Add document content before creating a PDF.");return;}setBusy(true);setError(null);setWarnings([]);setOutput(null);const controller=new AbortController();abortRef.current=controller;try{setProgress(pdfMode==="searchable"?"Building searchable PDF…":"Rendering visual PDF pages…");const request={layout,metadata,style};let nextBytes:Uint8Array;let nextWarnings:string[]=[];if(pdfMode==="searchable"){const result=await buildSearchablePdf(request,controller.signal);nextBytes=result.bytes;nextWarnings=result.report.warnings;}else{const result=await buildVisualCreatorPdf(request,controller.signal,(done,total)=>setProgress(`Rendering page ${done}/${total}…`));nextBytes=result.bytes;nextWarnings=result.warnings;}setProgress("Validating PDF…");const summary=await inspectPdfBytes(nextBytes);if(summary.pageCount!==layout.pages.length)throw new Error(`Generated PDF contains ${summary.pageCount} pages; expected ${layout.pages.length}.`);setOutput(nextBytes);setWarnings(nextWarnings);setProgress("PDF ready");}catch(reason){if(!(reason instanceof DOMException&&reason.name==="AbortError"))setError(reason instanceof Error?reason.message:String(reason));}finally{setBusy(false);abortRef.current=null;}}
  async function saveProject(){if(!output)return;setBusy(true);setError(null);try{const name=filename(metadata.title);const project=await createProjectFromBytes(output,name,"application/pdf",undefined,{deduplicate:false,displayName:metadata.title||name.replace(/\.pdf$/i,""),operation:"create-pdf-studio"});navigateTo({name:"workspace",projectId:project.id,mode:"viewer"});}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}finally{setBusy(false);}}
  const numberField=(label:string,value:number,onChange:(value:number)=>void,min:number,max:number,step=.5)=><label className="creator-field"><span>{label}</span><input min={min} max={max} step={step} type="number" value={value} onChange={event=>onChange(Number(event.target.value))}/></label>;
  return <div className="creator-page"><section className="tools-hero creator-hero"><div><p className="eyebrow">Create PDF</p><h2>Create polished PDFs directly in the browser.</h2><p>Write or paste Markdown, plain text, or simple HTML, choose page styling, preview the result, and export locally.</p></div><div className="creator-hero__actions"><button className="button button--secondary" onClick={()=>fileRef.current?.click()} type="button">Import source</button><input ref={fileRef} hidden accept=".md,.markdown,.txt,.html,.htm,text/plain,text/markdown,text/html" type="file" onChange={event=>{const file=event.target.files?.[0];if(file)void importSource(file);event.target.value="";}}/></div></section>
    {error?<div className="error-banner"><strong>Create PDF issue</strong><span>{error}</span></div>:null}{warnings.length?<div className="warning-banner"><strong>Output notes</strong><span>{warnings.join(" ")}</span></div>:null}
    <div className="creator-shell"><aside className="creator-settings"><section><h3>Document</h3><label>Title<input value={metadata.title} onChange={event=>{setMetadata({...metadata,title:event.target.value});invalidate();}}/></label><label>Author<input value={metadata.author} onChange={event=>{setMetadata({...metadata,author:event.target.value});invalidate();}}/></label><label>Input format<select value={mode} onChange={event=>{setMode(event.target.value as CreatorInputMode);invalidate();}}><option value="markdown">Markdown</option><option value="text">Plain text</option><option value="html">Semantic HTML</option></select></label></section>
      <section><h3>Style preset</h3><label>Preset<select value={presetId} onChange={event=>loadPreset(event.target.value)}>{presets.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div className="creator-preset-save"><input aria-label="Preset name" value={presetName} onChange={event=>setPresetName(event.target.value)}/><button className="button button--tiny" onClick={()=>{const saved=saveCreatorPreset(presetName,style);setPresets(listCreatorPresets());setPresetId(saved.id);}} type="button">Save</button></div>{!presetId.startsWith("builtin-")?<button className="button button--ghost button--tiny" onClick={()=>{deleteCreatorPreset(presetId);setPresets(listCreatorPresets());loadPreset(BUILTIN_CREATOR_PRESETS[0].id);}} type="button">Delete custom preset</button>:null}</section>
      <section><h3>Page</h3><label>Size<select value={style.pagePreset} onChange={event=>changeStyle({pagePreset:event.target.value as CreatorStyle["pagePreset"]})}><option value="a4">A4 · 210 × 297 mm</option><option value="a5">A5 · 148 × 210 mm</option><option value="custom">Custom</option></select></label>{style.pagePreset==="custom"?<div className="creator-grid-2">{numberField("Width (mm)",style.customWidthMm,value=>changeStyle({customWidthMm:value}),80,500,1)}{numberField("Height (mm)",style.customHeightMm,value=>changeStyle({customHeightMm:value}),80,500,1)}</div>:null}<div className="creator-grid-2">{numberField("Top (mm)",style.marginTopMm,value=>changeStyle({marginTopMm:value}),5,80,1)}{numberField("Right (mm)",style.marginRightMm,value=>changeStyle({marginRightMm:value}),5,80,1)}{numberField("Bottom (mm)",style.marginBottomMm,value=>changeStyle({marginBottomMm:value}),5,80,1)}{numberField("Left (mm)",style.marginLeftMm,value=>changeStyle({marginLeftMm:value}),5,80,1)}</div></section>
      <section><h3>Typography</h3><label>Family<select value={style.fontFamily} onChange={event=>changeStyle({fontFamily:event.target.value as CreatorStyle["fontFamily"]})}><option value="sans">Sans serif</option><option value="serif">Serif</option></select></label><div className="creator-grid-2">{numberField("Body (pt)",style.bodySizePt,value=>changeStyle({bodySizePt:value}),7,24,.5)}{numberField("Line height",style.lineHeight,value=>changeStyle({lineHeight:value}),1,2.2,.05)}{numberField("Paragraph gap (pt)",style.paragraphGapPt,value=>changeStyle({paragraphGapPt:value}),0,36,1)}{numberField("Heading scale",style.headingScale,value=>changeStyle({headingScale:value}),.8,1.5,.05)}</div></section>
      <section><h3>Running content</h3><label>Header<input value={style.headerText} onChange={event=>changeStyle({headerText:event.target.value})}/></label><label>Footer<input value={style.footerText} onChange={event=>changeStyle({footerText:event.target.value})}/></label><label className="checkbox-row"><input checked={style.pageNumbers} type="checkbox" onChange={event=>changeStyle({pageNumbers:event.target.checked})}/><span>Page numbers</span></label>{style.pageNumbers?numberField("First number",style.firstPageNumber,value=>changeStyle({firstPageNumber:value}),1,9999,1):null}</section>
      <section><h3>PDF output</h3><label>Mode<select value={pdfMode} onChange={event=>{setPdfMode(event.target.value as CreatorPdfMode);invalidate();}}><option value="searchable">Searchable text PDF</option><option value="visual">Visual compatibility PDF</option></select></label><p className="muted">{pdfMode==="searchable"?"Keeps Latin and CJK text searchable/selectable, including inline emphasis and clickable safe links. Shaping-dependent scripts are blocked rather than exported incorrectly.":"Uses browser text shaping and rasterizes pages. Best compatibility, but PDF text is not selectable/searchable."}</p></section>
    </aside><main className="creator-workspace"><div className="creator-editor"><div className="creator-pane-title"><strong>Source</strong><span>{source.length.toLocaleString()} characters</span></div><textarea aria-label="Document source" spellCheck value={source} onChange={event=>{setSource(event.target.value);invalidate();}}/></div><div className="creator-preview"><div className="creator-pane-title"><strong>Preview</strong><span>{layout.pages.length} page{layout.pages.length===1?"":"s"}</span></div><div className={`creator-paper creator-paper--${style.fontFamily}`} style={{fontSize:`${Math.max(9,style.bodySizePt)}px`,lineHeight:style.lineHeight,padding:`${Math.max(18,style.marginTopMm*1.2)}px ${Math.max(18,style.marginRightMm*1.2)}px ${Math.max(18,style.marginBottomMm*1.2)}px ${Math.max(18,style.marginLeftMm*1.2)}px`}}><CreatorPreview blocks={blocks}/></div></div></main></div>
    <footer className="creator-output-bar"><div><strong>{output?"PDF ready":`${layout.pages.length} page${layout.pages.length===1?"":"s"} planned`}</strong><span>{output?`${(output.byteLength/1_000_000).toFixed(2)} MB · ${pdfMode==="searchable"?"searchable":"visual"}`:progress||"Edit the source or page settings, then create the PDF."}</span></div>{busy?<button className="button button--secondary" onClick={()=>abortRef.current?.abort()} type="button">Cancel</button>:<button className="button" onClick={()=>void generate()} type="button">Create PDF</button>}{output?<><button className="button button--secondary" onClick={()=>downloadBlob(new Blob([Uint8Array.from(output).buffer],{type:"application/pdf"}),filename(metadata.title))} type="button">Download</button><button className="button button--secondary" disabled={busy} onClick={()=>void saveProject()} type="button">Save as project</button></>:null}</footer>
  </div>;
}

function InlinePreview({runs,text}:{runs?:CreatorInlineRun[];text:string}){const values=runs?.length?runs:[{text,style:"normal" as const}];return <>{values.map((run,index)=>{if(run.style==="bold")return <strong key={index}>{run.text}</strong>;if(run.style==="italic")return <em key={index}>{run.text}</em>;if(run.style==="bold-italic")return <strong key={index}><em>{run.text}</em></strong>;if(run.style==="code")return <code key={index}>{run.text}</code>;if(run.style==="link"&&run.href)return <a href={run.href} key={index} rel="noreferrer" target="_blank">{run.text}</a>;return <span key={index}>{run.text}</span>;})}</>;}
function CreatorPreview({blocks}:{blocks:CreatorBlock[]}){return <div className="creator-preview-content">{blocks.map((block,index)=>{if(block.type==="heading"){const value=<InlinePreview runs={block.runs} text={block.text}/>;if(block.level===1)return <h1 key={index}>{value}</h1>;if(block.level===2)return <h2 key={index}>{value}</h2>;if(block.level===3)return <h3 key={index}>{value}</h3>;if(block.level===4)return <h4 key={index}>{value}</h4>;if(block.level===5)return <h5 key={index}>{value}</h5>;return <h6 key={index}>{value}</h6>;}if(block.type==="paragraph")return <p key={index}><InlinePreview runs={block.runs} text={block.text}/></p>;if(block.type==="bullet")return <div className="creator-preview-list" key={index}>• <InlinePreview runs={block.runs} text={block.text}/></div>;if(block.type==="numbered")return <div className="creator-preview-list" key={index}>{block.number}. <InlinePreview runs={block.runs} text={block.text}/></div>;if(block.type==="quote")return <blockquote key={index}><InlinePreview runs={block.runs} text={block.text}/></blockquote>;if(block.type==="code")return <pre key={index}><code>{block.text}</code></pre>;return <hr key={index}/>;})}</div>;}
