import { useEffect, useRef, useState } from "react";
import type { PDFDocumentProxy } from "pdfjs-dist";
import { inspectDetailedPdf, openPdfWithPdfJs, type DetailedPdfInspection } from "../engines/pdfjs";
import { downloadBlob } from "../projects/download";
import { getProject, loadProjectBytes } from "../projects/projectRepository";
import { inspectSecurity } from "../security/securityClient";
import type { SecurityInspectionReport } from "../types/security";
import type { ProjectManifest } from "../types/project";

interface Props { projectId: string; onTitleChange?: (title: string, subtitle?: string) => void }
export function InspectorPage({ projectId, onTitleChange }: Props) {
  const documentRef=useRef<PDFDocumentProxy|null>(null), abortRef=useRef<AbortController|null>(null);
  const [project,setProject]=useState<ProjectManifest|null>(null),[details,setDetails]=useState<DetailedPdfInspection|null>(null),[security,setSecurity]=useState<SecurityInspectionReport|null>(null),[progress,setProgress]=useState(0),[status,setStatus]=useState("Opening…"),[error,setError]=useState<string|null>(null),[password,setPassword]=useState(""),[passwordRequired,setPasswordRequired]=useState(false);
  useEffect(()=>{let cancelled=false;void(async()=>{try{const manifest=await getProject(projectId);if(!manifest)throw new Error("Project not found.");const bytes=await loadProjectBytes(manifest);if(cancelled)return;setProject(manifest);await runInspection(manifest,bytes);}catch(reason){setError(reason instanceof Error?reason.message:String(reason));setStatus("Failed");}})();return()=>{cancelled=true;abortRef.current?.abort();void documentRef.current?.loadingTask.destroy();};},[projectId]);
  async function runInspection(manifest:ProjectManifest,bytes:Uint8Array,suppliedPassword?:string){setError(null);setStatus("Opening PDF…");try{const doc=await openPdfWithPdfJs(bytes,suppliedPassword);documentRef.current=doc;setPasswordRequired(false);onTitleChange?.(`Inspect · ${manifest.name}`,`${doc.numPages} pages · Structural, resource, and security report.`);const controller=new AbortController();abortRef.current=controller;setStatus("Inspecting pages…");const [detail,securityReport]=await Promise.all([inspectDetailedPdf(doc,controller.signal,(c,t)=>setProgress(c/t)),inspectSecurity(bytes,suppliedPassword,controller.signal)]);setDetails(detail);setSecurity(securityReport);setStatus("Inspection complete");setProgress(1);}catch(reason){const message=reason instanceof Error?reason.message:String(reason);if(/password|encrypted/i.test(message)){setPasswordRequired(true);setError("Enter the PDF password. It is not stored.");}else throw reason;}}
  function exportReport(){if(!details||!security||!project)return;downloadBlob(new Blob([JSON.stringify({generatedAt:new Date().toISOString(),project:{name:project.name,filename:project.sourceFilename,bytes:project.byteLength},details,security},null,2)],{type:"application/json"}),`${project.name}-inspection.json`);}
  return <div className="inspector-page"><aside className="inspector-summary"><p className="eyebrow">Document inspector</p><h2>Document structure report</h2><p>Inspect pages, text, fonts, image drawing operations, forms, annotations, attachments, actions, revisions, and security.</p>{error?<div className="error-banner"><strong>Inspection issue</strong><span>{error}</span></div>:null}{passwordRequired?<section className="password-panel"><input autoFocus autoComplete="off" onChange={e=>setPassword(e.target.value)} placeholder="PDF password" type="password" value={password}/><button className="button" disabled={!password||!project} onClick={()=>project&&void loadProjectBytes(project).then(bytes=>runInspection(project,bytes,password))} type="button">Inspect</button></section>:null}<div className="metric-stack"><div><strong>{details?.pageCount??"—"}</strong><span>Pages</span></div><div><strong>{details?.totals.uniqueFonts??"—"}</strong><span>Fonts</span></div><div><strong>{details?.totals.imageOperations??"—"}</strong><span>Image operations</span></div><div><strong>{security?.formFields.length??"—"}</strong><span>Form fields</span></div><div><strong>{security?.signatures.length??"—"}</strong><span>Signatures</span></div><div><strong>{security?.versionCount??"—"}</strong><span>Revisions</span></div></div><button className="button button--wide" disabled={!details||!security} onClick={exportReport} type="button">Export JSON report</button></aside>
  <main className="inspector-results"><header className="processing-header"><div><strong>{status}</strong><span>{project?`${(project.byteLength/1024/1024).toFixed(2)} MB · ${project.sourceFilename}`:""}</span></div>{progress<1?<progress max="1" value={progress}/>:null}</header>{details&&security?<><section className="inspection-grid"><article><h3>Security</h3><dl><div><dt>Encryption</dt><dd>{security.encryptionDescription}</dd></div><div><dt>Authentication</dt><dd>{security.authentication}</dd></div><div><dt>Repair detected</dt><dd>{security.repaired?"Yes":"No"}</dd></div><div><dt>Change history</dt><dd>{security.versionCount} revisions</dd></div></dl></article><article><h3>Interactive content</h3><dl><div><dt>Annotations</dt><dd>{security.annotationCount}</dd></div><div><dt>Links</dt><dd>{security.linkCount}</dd></div><div><dt>Attachments</dt><dd>{security.attachmentCount}</dd></div><div><dt>JavaScript</dt><dd>{security.hasJavaScript?"Present":"None detected"}</dd></div></dl></article><article><h3>Structure</h3><dl><div><dt>Outline entries</dt><dd>{details.outlineEntries}</dd></div><div><dt>Text characters</dt><dd>{details.totals.textCharacters.toLocaleString()}</dd></div><div><dt>Form widgets</dt><dd>{details.totals.widgets}</dd></div><div><dt>Metadata fields</dt><dd>{Object.keys(details.metadata).length}</dd></div></dl></article></section><section className="page-report-table"><header><strong>Page report</strong><span>{details.pages.length} rows</span></header><div className="table-scroll"><table><thead><tr><th>Page</th><th>Size</th><th>Rotation</th><th>Text</th><th>Fonts</th><th>Images</th><th>Annotations</th><th>Links</th><th>Widgets</th></tr></thead><tbody>{details.pages.map(page=><tr key={page.pageNumber}><td>{page.pageNumber}</td><td>{Math.round(page.width)}×{Math.round(page.height)}</td><td>{page.rotation}°</td><td>{page.textCharacters}</td><td>{page.fontNames.length}</td><td>{page.imageOperations}</td><td>{page.annotationCount}</td><td>{page.linkCount}</td><td>{page.widgetCount}</td></tr>)}</tbody></table></div></section></>:<div className="empty-state"><strong>Inspection running</strong><p>Large documents are processed page by page to keep the interface responsive.</p></div>}</main></div>;
}
