import * as mupdf from "mupdf";
import type { CreatorBuildRequest, CreatorFontFamily, CreatorFontRole, CreatorPageCommand } from "../types/creator";

type CreateRequest={type:"CREATE";requestId:string;request:CreatorBuildRequest};type CancelRequest={type:"CANCEL";requestId:string};type Request=CreateRequest|CancelRequest;
const cancelled=new Set<string>();
function active(id:string){if(cancelled.has(id))throw new DOMException("Operation cancelled.","AbortError");}
function utf16Hex(text:string):string{let hex="feff";for(let index=0;index<text.length;index+=1)hex+=text.charCodeAt(index).toString(16).padStart(4,"0");return`<${hex}>`;}
function script(text:string):"ko"|"ja"|"zh-Hans"|undefined{if(/[\uac00-\ud7af\u1100-\u11ff]/u.test(text))return"ko";if(/[\u3040-\u30ff]/u.test(text))return"ja";if(/[\u3400-\u9fff]/u.test(text))return"zh-Hans";return undefined;}
function assertSearchableScript(text:string):void{if(/[\u0590-\u08ff\u0900-\u0dff\u0e00-\u0e7f]/u.test(text))throw new Error("This document contains a shaping-dependent script. Use Visual compatibility PDF so the browser can shape the text correctly.");}
function face(family:CreatorFontFamily,role:CreatorFontRole):string{if(role==="mono")return"Courier";if(family==="serif"){if(role==="bold")return"Times-Bold";if(role==="italic")return"Times-Italic";if(role==="bold-italic")return"Times-BoldItalic";return"Times-Roman";}if(role==="bold")return"Helvetica-Bold";if(role==="italic")return"Helvetica-Oblique";if(role==="bold-italic")return"Helvetica-BoldOblique";return"Helvetica";}
function fontKey(command:Extract<CreatorPageCommand,{type:"text"}>):string{return`${script(command.text)??"unicode"}|${command.fontFamily}|${command.fontRole}`;}
function makeFont(pdf:any,command:Extract<CreatorPageCommand,{type:"text"}>):any{assertSearchableScript(command.text);const language=script(command.text);if(language)return pdf.addCJKFont(new (mupdf as any).Font(language),language,0,command.fontFamily==="serif"?"serif":"sans-serif");return pdf.addFont(new (mupdf as any).Font(face(command.fontFamily,command.fontRole)));}
function contentFor(pageHeight:number,commands:CreatorPageCommand[],fontNames:Map<string,string>):string{const chunks:string[]=[];for(const command of commands){if(command.type==="rule"){const y=pageHeight-command.yTopPt;chunks.push(`q ${command.gray.toFixed(3)} G .6 w ${command.xPt.toFixed(3)} ${y.toFixed(3)} m ${(command.xPt+command.widthPt).toFixed(3)} ${y.toFixed(3)} l S Q\n`);continue;}assertSearchableScript(command.text);const key=fontKey(command),name=fontNames.get(key);if(!name)throw new Error("Creator font resource is missing.");const y=pageHeight-command.yTopPt;chunks.push(`q ${command.gray.toFixed(3)} g BT /${name} ${command.fontSizePt.toFixed(2)} Tf 1 0 0 1 ${command.xPt.toFixed(3)} ${y.toFixed(3)} Tm ${utf16Hex(command.text)} Tj ET Q\n`);if(command.underline&&command.widthPt){const uy=y-1.2;chunks.push(`q ${command.gray.toFixed(3)} G .55 w ${command.xPt.toFixed(3)} ${uy.toFixed(3)} m ${(command.xPt+command.widthPt).toFixed(3)} ${uy.toFixed(3)} l S Q\n`);}}return chunks.join("");}
function setMetadata(pdf:any,request:CreatorBuildRequest):void{const entries:{[key:string]:string}={Title:request.metadata.title,Author:request.metadata.author,Subject:request.metadata.subject,Keywords:request.metadata.keywords,Creator:"PDF Studio",Producer:"PDF Studio"};for(const[key,value]of Object.entries(entries))if(value.trim())pdf.setMetaData(`info:${key}`,value.trim());}
function save(pdf:any):Uint8Array{pdf.check?.();const buffer=pdf.saveToBuffer("garbage=4,clean=yes,compress=yes,compress-fonts=yes");try{return Uint8Array.from(buffer.asUint8Array());}finally{buffer.destroy();}}
self.onmessage=(event:MessageEvent<Request>)=>{const message=event.data;if(message.type==="CANCEL"){cancelled.add(message.requestId);return;}const started=performance.now();try{active(message.requestId);const request=message.request,pdf=new (mupdf as any).PDFDocument();try{setMetadata(pdf,request);for(let pageIndex=0;pageIndex<request.layout.pages.length;pageIndex+=1){active(message.requestId);const commands=request.layout.pages[pageIndex].commands;const fonts=pdf.newDictionary();const resources=pdf.newDictionary();resources.put("Font",fonts);const fontNames=new Map<string,string>();let sequence=0;for(const command of commands){if(command.type!=="text")continue;const key=fontKey(command);if(fontNames.has(key))continue;const name=`F${++sequence}`;fonts.put(name,makeFont(pdf,command));fontNames.set(key,name);}const resourceRef=pdf.addObject(resources);const page=pdf.addPage([0,0,request.layout.pageWidthPt,request.layout.pageHeightPt],0,resourceRef,contentFor(request.layout.pageHeightPt,commands,fontNames));pdf.insertPage(-1,page);for(const command of commands){if(command.type!=="text"||!command.linkUrl||!command.widthPt)continue;try{page.createLink([command.xPt,Math.max(0,command.yTopPt-command.fontSizePt*1.1),command.xPt+command.widthPt,command.yTopPt+command.fontSizePt*.25],command.linkUrl);}catch{}}page.destroy?.();}
      const output=save(pdf),buffer=output.buffer.slice(output.byteOffset,output.byteOffset+output.byteLength);self.postMessage({type:"CREATOR_RESULT",requestId:message.requestId,output:buffer,report:{pageCount:request.layout.pages.length,outputBytes:output.byteLength,searchable:true,warnings:request.layout.warnings,durationMs:performance.now()-started}},[buffer]);
    }finally{pdf.destroy();}}catch(error){self.postMessage({type:"CREATOR_ERROR",requestId:message.requestId,error:error instanceof Error?{name:error.name,message:error.message}:{name:"UnknownError",message:String(error)}});}finally{cancelled.delete(message.requestId);}};
export{};
